export const FETCH_DEFAULT_MOVIES_REQUEST = "FETCH_DEFAULT_MOVIES_REQUEST";
export const FETCH_DEFAULT_MOVIES_FULFILLED = "FETCH_DEFAULT_MOVIES_FULFILLED";
export const FETCH_DEFAULT_MOVIES_REJECTED = "FETCH_DEFAULT_MOVIES_REJECTED";
