export const FETCH_DEFAULT_MOVIES_REQUEST = "FETCH_DEFAULT_MOVIES_REQUEST";
export const FETCH_DEFAULT_MOVIES_FULFILLED = "FETCH_DEFAULT_MOVIES_FULFILLED";
export const FETCH_DEFAULT_MOVIES_REJECTED = "FETCH_DEFAULT_MOVIES_REJECTED";

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_FULFILLED = "SEARCH_MOVIES_FULFILLED";
export const SEARCH_MOVIES_REJECTED = "FETCH_DEFAULT_MOVIES_REJECTED";
