import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import loader from "../public/assets/gifs/loader.gif";
import ActionTabs from "../component/ActionTabs";
import WelcomeContainer from "../src/WelcomeContainer";
import fetchMoviesAction from "../store/actions/fetchMovies";
import selectFetchMovies from "../store/selectors/fetchMovies";

export default function Home({ router }) {
  const { fetchMovies } = fetchMoviesAction();
  const { movies, isLoadingMovies } = useSelector(selectFetchMovies);
  const [option, setOption] = useState(0);
  const options = ["Action", "Drama", "Sci-Fi", "Horror"];
  useEffect(() => {
    fetchMovies(options[option]);
  }, [fetchMovies, option]);

  return (
    <>
      <Head>
        <title>ImDb Movies & Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ActionTabs router={router} setOption={setOption} />

        {isLoadingMovies && (
          <div className="loaderComponent">
            <Image src={loader} alt="loader" />
          </div>
        )}
        {!isLoadingMovies && <WelcomeContainer />}
        <div>
          {movies?.map((movie) => (
            <h1 key={movie.imdbID}>{JSON.stringify(movie)}</h1>
          ))}
        </div>
      </main>
    </>
  );
}
