import Head from "next/head";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import ActionTabs from "../component/ActionTabs";
import WelcomeContainer from "../src/WelcomeContainer";
import fetchMoviesAction from "../store/actions/fetchMovies";
import selectFetchMovies from "../store/selectors/fetchMovies";

export default function Home({ router }) {
  const { fetchMovies } = fetchMoviesAction();
  const { movies } = useSelector(selectFetchMovies);
  useEffect(() => {
    fetchMovies();
  }, [fetchMovies]);

  return (
    <>
      <Head>
        <title>ImDb Movies & Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ActionTabs router={router} />
        <WelcomeContainer />
        <div>
          {movies?.map((movie) => (
            <h1 key={movie.imdbID}>{JSON.stringify(movie)}</h1>
          ))}
        </div>
      </main>
    </>
  );
}
