import Head from "next/head";
import ActionTabs from "../component/ActionTabs";
import WelcomeContainer from "../src/WelcomeContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>ImDb Movies & Shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ActionTabs />
        <WelcomeContainer />
      </main>
    </>
  );
}
